### ISSUE TITLE
Idea: friendlier names and descriptions

### ISSUE THREAD

**Issue by brampitoyo** [jonathanKingston/paranoidpanda#1]
Since level 1 (“low”) equals the same level of protection that Firefox already provides (other than the two hidden prefs), perhaps we should label it “off”?

Level 2 could be called “secure” or “more secure” – and level 3 “paranoid”.

Now, how to describe these levels?

We can either go with a technical description, like:

> Secure
> - Tracking Protection enabled on normal browsing
> - HTTP header is trimmed
> - DNS prefetching is disabled
> - Insert bits about cookies here
> - etc.

Or we can make it less technical, like:

> Secure
> Tracking protection is enabled everywhere, and sharing your personal browsing data is limited, but it won’t break many sites
> 
> Paranoid
> All security settings enabled. Consequently, some sites will break.

Thoughts?

**Comment by jonathanKingston** [comment]
Yup agreed, added thank you @brampitoyo!

**Comment by jonathanKingston** [comment]
To clarify I went with less technical, as we can always implement a more info or tech info link etc.
